### ISSUE TITLE
What is the best way to implement code ligatures? With dlig or calt? Same or separate font?

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#106]
Code ligatures are not always readable to people who are unfamiliar with them. They also add a fair number of glyphs and coordinates to a font, and therefore add a significant amount of data to final font files. 

We should be sure that:
- Code ligatures are not on by default
- In web fonts served by Google Fonts, code ligatures ~~are split into an extended Unicode range, rather than served with the initial, basic Latin charset (https://github.com/google/fonts/issues/2103)~~ are not served if users do not want to use that feature
- If there are specific Recursive Sans font files, code ligatures are subset out.

**Comment by arrowtype** [comment]
Code ligatures are not subset out of the most simple downloads from Google Fonts, and probably can't be any time soon (without a change also happening in CSS and browsers for the `unicode-range` property). This means that:

1. They download every time

They are also contextual ligatures (at least in the case of Fira Code, which probably reflects what code editors expect for ligatures), rather than discretionary ligatures. This means that:

2. They are on by default every time

These two things would obviously not be the appropriate behavior for the default version of Recursive.

So, I think I will follow the example of Fira Code and Cascadia Code, and make "Recursive Code" – a separate build of Recursive that has code ligatures. (I think Noemi Stauffer had this idea first. As it turns out, it's an even better idea than I initially realized!)

**Comment by arrowtype** [comment]
For reference:

[contextual ligatures](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-clig) are recommended to be "on" by default. Typically, this includes such combinations as `fi`, which may need ligatures to fix spacing issues.

[discretionary ligatures](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-dlig) are sometimes available to add more-expressive ligatures into text. This often is the case for ligatures like `st`.

**Comment by arrowtype** [comment]
UPDATE: I'm moving these planning notes to:

https://github.com/arrowtype/recursive/tree/master/docs/code-ligatures--implementation

([Here's a permalink to the current commit.](https://github.com/arrowtype/recursive/tree/0d7d88a8dbd74ac03de5e21430394fd2182240e2/docs/code-ligatures--implementation))

**Comment by arrowtype** [comment]
I may loop back on this and offer a version that uses clig, but I believe dlig to be the option that best follows the OT spec, so I will make that the main strategy.
