### ISSUE TITLE
Font style-linking is broken on macOS because "cursive" substring is in family name - FIXED by macOS 11 🎉

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#153]
UPDATE: I've tested various workarounds to determine the source of this issue. Test files and instructions to reproduce this are available at https://github.com/arrowtype/recursive/tree/master/docs/ribbi-style-linking-macOS ([permalink](https://github.com/arrowtype/recursive/tree/c1012997ed4ece4482060c51b24c5aef4d8a0eb8/docs/ribbi-style-linking-macOS)).

## Problem

Regular-Italic style isn't currently working in Recursive, as of [v1.037 statics](https://github.com/arrowtype/recursive/tree/d40ac817e6b4381bedb36534b8a1ac44cbb313b7/fonts_1.037) (as well as in earlier versions). 

## Examples

- In VS Code, calling the font family "Recursive Mono Casual Static" calls the _Italic_ instance.
- In TextEdit/Keynote/Sketch, changing from a Regular version of a font (e.g. Helvetica) to Recursive will go to the `Italic` instance. When I change back to another font, the Italic style sticks.

![Kapture 2020-02-09 at 14 22 11](https://user-images.githubusercontent.com/45946693/74108372-9868fd00-4b47-11ea-852f-915c5fed07d7.gif)

## Questions to answer

- Why might Recursive Mono Casual Static Italic be getting treated as the "Regular" or default instance?
- What heuristics are used by macOS to determine the "Regular" instance of a type family?
  - Weird thought: could the substring `cursive` be triggering macOS to determine Recursive is an Italic / Cursive family? **UPDATE: holy hell, I think this was exactly the issue 😳**
- Could name length be affecting this style-linking? E.g. is the family name too many characters for macOS to process properly?

## Extra context

In some code themes, italics are very important.

However, it is surprisingly difficult to make sure a font displays with italics, as expected.

![image](https://user-images.githubusercontent.com/7355414/63131097-8a686400-bf8a-11e9-97ef-ad4896e43f4e.png)

## Test

**These static fonts work**

![image](https://user-images.githubusercontent.com/7355414/63131137-ae2baa00-bf8a-11e9-86c2-a0cdcd434f75.png)

![image](https://user-images.githubusercontent.com/7355414/63131149-b4218b00-bf8a-11e9-839e-62321e7c3e93.png)

**These do not work**

![image](https://user-images.githubusercontent.com/7355414/63131215-e632ed00-bf8a-11e9-8e9a-580daefdd598.png)

![image](https://user-images.githubusercontent.com/7355414/63131223-ec28ce00-bf8a-11e9-9854-d6bd3138cf02.png)

![image](https://user-images.githubusercontent.com/7355414/63131275-1aa6a900-bf8b-11e9-9c6a-7e185813521f.png)

**Differences**

- The latter fonts have "Beta" at the start of Name ID 3. 
- The latter fonts have the name "Recursive," which may potentially be clashing with other fonts on the system / in the cache.

**Comment by arrowtype** [comment]
This issue is still a problem. :/

As an example: in VS Code, if I set the preferred font to nameID 1 or 16 ("Recursive Mono Casual Static"), the result is all-Italic (whereas I expect Regular with Italic comments, etc, as works with other fonts). If I use the postscript nameID 6 ("RecursiveMonoCslSt-Regular"), I can get the Regular, but no Italic comments.

I've also tried fiddling with fsSelection (it seemed that Regular had bit 9 set, "contains oblique glyphs"), but that seemingly doesn't have an effect on my issue.

The Style Map Family Name & Style Map Style Name in a way that _should_ be working well, but it's still showing issues. 

One thing that may be related is that often, there are issues where the Regular is treated as if it were an italic. For example, when I set text and then change it to Recursive, it will often be italic off the bat. And then, if I change it to an upright of Recursive, then into another font, it will be italic. So, clearly it seems that something is telling my mac that the Italic style is the "regular," but it's hard to say what might be doing that. The "Italic" name is everywhere I expect it to be in the TTX.

**Comment by arrowtype** [comment]
Ohhhh my god. I am fairly certain that the problem was that "Recursive" contains the substring `cursive`. I have heard that in the past, a font containing the substring `ita` would set off a similar issue.

However, if I change the font name to be simply "Arrowtype", things work just fine:

![image](https://user-images.githubusercontent.com/45946693/74108983-707c9800-4b4d-11ea-9c46-cd61170351de.png)

Further proving this theory: family names "xcursivex" and "Discursive" _also_ suffer from the same issue:

![Kapture 2020-02-09 at 15 15 18](https://user-images.githubusercontent.com/45946693/74109159-05cc5c00-4b4f-11ea-89f4-1366762c13d3.gif)

![Kapture 2020-02-09 at 15 16 29](https://user-images.githubusercontent.com/45946693/74109177-33190a00-4b4f-11ea-9a29-4392aa87b8f7.gif)

**Comment by benkiel** [comment]
To chime in: this comes from how MacOS handles style-linking as a combination of weight values, fsSelection bits, and custom heuristics. I have run into this mastering MVB’s Solitaire, as it contains `ita` (bug filed with Apple, 14928748, was marked as a dupe on Oct. 15, 2014). This started happening after 10.4.11 for `ita`. 

MacOS seems to be marking these fonts as italic just based on the font name (`ita` or `cursive`)

**Comment by giovanicascaes** [comment]
Could you please tell how to rename the fonts?

**Comment by arrowtype** [comment]
@giovanicascaes please see https://github.com/arrowtype/recursive/tree/master/docs/ribbi-style-linking-macOS for a script and description of my process

**Comment by arrowtype** [comment]
@giovanicascaes are you hoping to get these for coding? If so, let me know and I can put together some. :) I still have to figure out a better strategy for a public release, but I can make some specific in the mean time

**Comment by giovanicascaes** [comment]
Yes, it is for coding. I was checking this repo almost daily for a fix :)

**Comment by arrowtype** [comment]
Woah! Thanks for your patience, and sorry it took so long to find a fix/workaround. As you can probably guess, undocumented OS heuristics based on the font name itself is not something we expected to be the blocker, here. 😅

I've made some workaround fonts and posted them at https://github.com/arrowtype/recursive/tree/027cdeff6dd007ec9cd09030506a86bc45d956b2/fonts_1.037/rec_mono-for-code

For convenience, here's a zip download with these fonts: [rec_mono-for-code.zip](https://github.com/arrowtype/recursive/files/4178693/rec_mono-for-code.zip)

To get these working, install them as usual, then quit & restart your code editor. Potentially, you may need to restart your computer for font updates to take effect, but usually not in a case like this, where the family names are changed. Let me know if you have any issues getting these working!

**Comment by giovanicascaes** [comment]
Yeah, it is an unexpected issue, maybe some macOS legacy. It must be truly difficult to track such a problem.

Thank you very much for your promptness. Already using the new builds, they work perfectly! 

Wondering how can I give some feedback to you guys. Maybe the only thing I can tell you right now is that a semicursive italic variant, like Operator Mono or Dank Mono one's, would be very appreciated, since these are very popular typefaces, much of it because of that feature. Of course, it would be a lot of work, tough.

**Comment by arrowtype** [comment]
Great, thanks for letting me know that it’s working!

> a semicursive italic variant, like Operator Mono or Dank Mono one's, would be very appreciated

Thanks! In my view, this is already the case – almost all lowercase letters have specifically semi-cursive variants in the Italic styles. A single-story /a, long /f, simplified /i, /l, and /r, outstrokes on /n, /h, /s, etc. Of course, the italics don’t look cursive to the same degree because it doesn’t include things like the looped /l and /f and the scripty /r and /a. This is for two main reasons:

1. I don’t want to make something that already exists. Operator is a great design, and I’m not trying to compete with it or make a free alternative, but rather to make something original and unique.
2. To me, the “cursive” forms don’t seem as immediately readable and they don’t work that well within this design, aesthetically (especially due to the Linear–Casual axis). I’ve tried drawing them, and I just don’t think it looks that good.

Still, I’m not 100% against the idea, and it could potentially be the sort of thing added into a stylistic set or even a forked version. But, yes, it also becomes a factor of time: in the near term, I need to finish the project and do other work. In the long term, I may change my mind and add them in. 

(I’ll probably copy this explanation into a different issue, to keep things clean).

**Comment by davelab6** [comment]
> I’ve tried drawing them, and I just don’t think it looks that good.

I'm curious what these sketches look like :) No worries if they were not good enough to share with anyone outside your house though XD

**Comment by madig** [comment]
Consider renaming the font to "Rekursiv" :grin:

**Comment by arrowtype** [comment]
@madig it’s not such a bad idea ... I’d have to test that it didn’t trigger the same bug, though. 😄 The name is nice, it has good letters, it’s meaning is still fairly clear, it sounds sophisticated, and the linear styles *do* have a little bit of DIN influence in them...

I could also translate to another language. In Danish, the word is “Rekursive.”

But, my main idea is staying the course and keeping the name overall, but abbreviating it to “Rec Mono/Sans” for downloads.

“Recursive” works fine on the web. For local fonts, there are secondary benefits to shortening the name (fitting into MS Word menus better, for one). Plus, I’m guessing that most coders will have a better chance of remembering the English spelling than the German spelling.

Though, hmm. Most people will probably download it directly from Google Fonts, and they may not be able to use custom naming rules on the backend when generating static downloads from variable fonts. So, that puts me back to maybe changing the name, after all.

@davelab6 do you have a suggestion one way or the other?

**Comment by nickshanks** [comment]
"Recurs" might work. I would avoid "Rekursiv" because the heuristics probably cover multiple languages and/or are localised when the OS gets translated.

**Comment by arrowtype** [comment]
> I would avoid "Rekursiv" because the heuristics probably cover multiple languages

That's a good point – it does seem like that might be a big (and hard to predict) risk.

**Comment by phineasfrogg** [comment]
This is still an issue as of 12 July 2020. Is there a way for us to rename the files so we can use them correctly? I know the Rec Code files exist, but I want to be able to use the _proportional_ Casual variant in Mac apps without these italic style-linking problems. I'm not experienced enough with Python to build the fonts from scratch. The collection files that the release versions come in can't be opened in Glyphs.

**Comment by benkiel** [comment]
Hey @phineasfrogg, there isn't anything we can do to fix MacOS, though version 11 seems to fix this. I'll defer to @arrowtype about making re-named proportional set, like the Rec Code set.

**Comment by arrowtype** [comment]
Thanks @phineasfrogg and @benkiel!

Yes, by my testing of the first beta for macOS 11, this is fixed, thankfully. But, I know that isn't very helpful today.

Yes, this could hacked around with a small addition to release scripts, using FontTools to edit font names in a variant for macOS 10 with the family name set as "Rec" or "Rekursive" (this would need testing, though). The hard part is that the release downloads are already pretty confusing, and this would add another layer of directly included. And, this is hard to prioritize over other issues. I partly didn’t change the font name in order to maybe give Apple a nudge to fix this issue for other fonts (no idea if this influenced them or not). But, now that it _is_ fixed, I would be okay making a hacked version if only to link to it from this issue.

I will try to fit this in in the next few days, and update here if I can!

**Comment by phineasfrogg** [comment]
@arrowtype Thank you so much! 

I'm glad to know that Apple has fixed the problem in Big Sur, and look forward to using the final versions there. In the meantime, I'd be happy with a hacked version if you have the time to do that.
