### ISSUE TITLE
Re-evaluate exact instance weight progression

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#165]
Up til now, I have been taking a slightly flawed approach to the weight progression in named instances, which meant that:
1. Earlier, that my axis `map` wasn't quite making the effect I intended for it to make
2. More recently, that my `Light` and `Regular` named instances had `wght` values other than `300` and `400`.

The key is that axis map `output` values must describe the _master input_` values, and the `input` map values are the end-user inputs to achieve those master values. Yes, it's a bit confusing.

I had half figured this out, setting my `source` values to correspond to the `map` outputs ... but I hadn't also done this for the `instance` dimension values. 

Now that I've done this, I have named instances that properly correspond to what a user will see when they enter a `wght` value of 300, 400, etc. _However,_ because I had based my earlier designs on flawed assumptions, my weights will need to be adjusted.

For now, I'll try to just make it "linear" between the `450` value that feels close to a good regular, then set Medium and SemiBold at even steps between 450 and 700:
- Medium: 433
- SemiBold: 616

![image](https://user-images.githubusercontent.com/7355414/63739839-5e839300-c854-11e9-9a8a-6c9ff0aadb77.png)

For now, this is okaaaay, but this really needs some better proofing, at different sizes, for me to be fully confident in my approach.

**Comment by arrowtype** [comment]
![image](https://user-images.githubusercontent.com/45946693/67637708-98543280-f8b3-11e9-95f3-f6f1dc07ea8c.png)

![image](https://user-images.githubusercontent.com/45946693/67637713-a1450400-f8b3-11e9-852e-a412efe2d169.png)

Above: Default Helvetica versus Recursive Sans Regular. 

Recursive Sans Regular is slightly too light for easy readability, and becomes especially spindly on iOS. This is essential to adjust before publishing the minisite.

**Comment by arrowtype** [comment]
Question: can the weight range potentially go down one entire step further, to 200 / ExtraLight?

Currently, with the `A` weight masters set to `250` and the Regular instances set at `530`, it _still_ feels too light until the weight is pushed to `450`, or the equivalent of about `596` in the designspace. Because this is so much higher than 400, this leads me to think that I may have somewhat more of a weight range than I had previously thought.

A way to test this:
- make a web page to lay out several common fonts: probably helvetica, roboto, & SF text
  - it will be best if these are in blocks from 200 to 700, potentially
- also lay out recursive
- adjust CSS to determine appropriate weight match
- adjust designspace values to match that

**Comment by arrowtype** [comment]
One thing I'll test, as a quick variation: matching stem weights to SF, and seeing how much closer that feels to correct, before adjusting further. 

Current stem widths for Recursive, when scaled to xHeight: 526
- `Casual/Linear A`: 50 (xHeight: 526)
- `Casual/Linear B`: 146 (150 at normal xHeight of 540) 
- `Casual/Linear C`: 215 (225 at normal xHeight of 550)


SF Pro Text, stem widths at matching x-heights for letter `n`, when scaled to xHeight: 526
- `Lt`: 64 
- `Rg`: 84
- `Md`: 104
- `SB`: 119
- `Bd`: 138
- `Hv`: 167

I'll adjust my designspace to come close to these values, and refine from this seems like a good direction.

**Comment by arrowtype** [comment]
```
<map input="200" output="50" />
<map input="300" output="67.5" />
<map input="400" output="85" />
<map input="500" output="105" />
<map input="600" output="119" />
<map input="700" output="133" />
<map input="800" output="146" />
<map input="850" output="180.5" />
<map input="900" output="215" />
```

![image](https://user-images.githubusercontent.com/45946693/67709193-d7f24b80-f993-11e9-8842-34b9195ffd54.png)

Observations of this early test:
- The minimum weight of Recursive really is a "300," not a "200", as I tested out here.
- The "400" is now a bit too heavy, but less bad than before.
- "700" is definitely too heavy

**Comment by arrowtype** [comment]
```
<map input="300" output="50" />
<map input="400" output="75" />
<map input="500" output="89" />
<map input="600" output="103" />
<map input="700" output="118" />
<map input="800" output="146" />
<map input="850" output="180.5" />
<map input="900" output="215" />
```

Observations:
- Using [vf2s.py](https://github.com/arrowtype/recursive/blob/c2e17d6d542973406f472ff478e381c277ac288c/src/build-scripts/vf2s.py), I've verified that the `800` weight of the built Recursive VF is the exact same outline as the `800` master. (On this web test, at text size it looks bolder than I'm used to thinking of this weight, so I wanted to verify.)
- The `400` weight, now at a designspace value of `75`, looks just a bit light. After vf2s.py, I see that it's true stem width is 76 – pretty darn close to what I expected. I'll bump it up to `80`, and see if that might be the sweet spot. 
  - because `800` is somewhat "stuck" as its current weight and stuck at extrabold (heavier than bold, but much lighter than the `C` weight masters), I will try setting values in between Regular and ExtraBold in a linear progression. This will make `700` heavier than other fonts, but I think that's a good compromise for this system. Regular has to closely match common fonts to be easily readable for users, while Bold just has to be clearly bolder than Regular. 

![image](https://user-images.githubusercontent.com/45946693/67710902-4b498c80-f997-11e9-941d-8b4a6c943269.png)

<details><summary><b>Useful script to calculate steps</b> (Click to expand)</summary>

```Python
valA = 80
valB = 146
steps = 4

def getSteps(valA, valB, steps):
    totalRange = valB - valA
    stepSize = totalRange / steps
    
    for step in range(steps):
        valA += stepSize
        print(valA)   
    
getSteps(valA, valB, steps)
```

</details>

**Comment by arrowtype** [comment]
```
<map input="300" output="50" />
<map input="400" output="80" />
<map input="500" output="96.5" />
<map input="600" output="113" />
<map input="700" output="113.5" />
<map input="800" output="146" />
<map input="850" output="180.5" />
<map input="900" output="215" />
```

Observations:
- The `80` weight value appears just a bit light. I'd rather be a bit bolder than a bit lighter.
- With a more-similar thickness to letters, it's very apparent that the spacing is looser in Recursive. This is really due to its being designed primarily for smaller sizes in code contexts, then subsequently adapted for proportional text. Potentially, in the future, this should get an optical size axis.
- It is also fairly clear that the "body size" of Recursive is bigger than SF Pro Text, Roboto, and Helvetica Neue. I will need to next investigate vertical metrics a bit more closely, to make sure I'm hitting these correctly. I want "16px" in Recursive to look pretty close to "16px" in system fonts.

![image](https://user-images.githubusercontent.com/45946693/67713887-16d8cf00-f99d-11e9-95ec-a32d782c74d5.png)

**Comment by arrowtype** [comment]
```
<map input="300" output="50" />
<map input="400" output="83" />
<map input="500" output="98.75" />
<map input="600" output="114.5" />
<map input="700" output="130.25" />
<map input="800" output="146" />
<map input="850" output="180.5" />
<map input="900" output="215" />
```

Closer... but still quite a bit heavier in the `700` instance. @sponcey suggested maybe trying a top weight of 1000, so I'll give that a go.

![image](https://user-images.githubusercontent.com/45946693/67718250-c154f000-f9a5-11e9-90b9-baf284375f31.png)

**Comment by arrowtype** [comment]
This has been a much more challenging issue to nail down than I had expected.

I have recorded the difficulties here: https://github.com/fonttools/fonttools/issues/1756

For now, I will pause on this issue. I am relatively happy with the weight progression on Mac, and especially happy with it when it renders correctly when viewed in Windows 10 (via VM Ware).

<details><summary><b>Weight progression w/ AVAR, on Windows 10</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/45946693/67807011-591c1200-fa6a-11e9-9c2f-93c6bc219649.png)

</details>

I may find/resolve whatever inconsistency is causing this, as I incorporate more up-to-date sources into my build process.

**Comment by arrowtype** [comment]
Next steps on this:

- create drawbot script to layout similar test and check weight AVAR with this output

**Comment by arrowtype** [comment]
I have come to the conclusion that it isn’t worthwhile matching fallback-font weights too extremely closely, as the overall style here is fairly different, so a fairly similar color is good already. Once front weight AVAR mapping is better supported in macOS, the progression of weights is satisfactory, here.
