### ISSUE TITLE
Fix accent in /Lslash

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive#173]
As of [this latest proof](https://github.com/arrowtype/recursive/blob/d2d7779d839c1930b2c92670112a1cb395f58527/src/proofs/working-proofs/092019-geometric-shapes/Recursive-geometricshapes-and-more-20190923.pdf), the /Lslash has a slash that is too far to the left, so it crashes into letters before itself.

The slash is currently centered on the L stem, but it should be more to the middle of the glyph's space.

![image](https://user-images.githubusercontent.com/45946693/65454680-a5dd4f00-de13-11e9-923e-29e188952719.png)

Here's a variety of /Lslash glyphs in sans-serif fonts with better positioning of the slash:

![image](https://user-images.githubusercontent.com/45946693/65454926-2439f100-de14-11e9-98e3-ef08ef6f7d06.png)

**Comment by LisaHuang2017** [comment]
<img width="438" alt="Capture d’écran 2019-09-24 à 16 27 51" src="https://user-images.githubusercontent.com/32390132/65520688-48ff9880-dee8-11e9-82d1-29407c9825c6.png">
I'll add a /slashcomb.case to differentiate the slash on uppercase /L and lowercase /l letters, otherwise this issue shown in the picture wouldn't make sense...

**Comment by LisaHuang2017** [comment]
Better result: 
<img width="422" alt="Capture d’écran 2019-09-24 à 16 31 44" src="https://user-images.githubusercontent.com/32390132/65521011-d6db8380-dee8-11e9-91e6-009762ada2be.png">

**Comment by LisaHuang2017** [comment]
After last check from merging PR (https://github.com/arrowtype/recursive/pull/175), this issue can be closed
