### ISSUE TITLE
XPRN considered harmful

### ISSUE THREAD

**Issue by davelab6** [arrowtype/recursive#201]
Expression / XPRN might be too vague for an axis.  What are some other options?

Generally, can you define all the axes in the project source tree somewhere, with at least all the fields in the Microsoft Axes proposal repo? :)

**Comment by arrowtype** [comment]
> Expression / XPRN might be too vague for an axis. What are some other options?

"Casual" `CASL` is the only alternative that I like, so far.

**Pros:** 

- We have already updated the "Proportion" axis to have the name "Monospace," and "Casual" would be a similar linguistic and semantic approach. 
- Similar to the "Monospace" axis, "Casual" would describe the style of text present when the axis is turned to 1. `0` would be what people will probably find more generally applicable, while `1` would be meant for more-specific usage. When Casual is `0`, text is meant for rigorous, focused usage. When Casual is `1`, text is meant for more casual, generally shorter, more entertaining usage. 
- This is also similar to the 0–1 "Italic" registered axis.
- Casual is a stylistic term fairly specific  and limited to Recursive (or other fonts based on casual signpainting). In this sense, it would be a bit like specific axis names like Yeast, Gravity, and Temperature in [Cheee, by OHno Type Co](https://www.futurefonts.xyz/ohno/cheee).

**Cons:** 

- Most familiar variable axes are attributes with a numeric scale – weight, width, optical size, slant. So, potentially, it makes the most sense to give new variation axes names that are visual attributes that can have numeric scales. If this is desired, then axis names such as "Proportion" and "Expression" are more in line with this approach. 
- If we _do_ decide that it would be useful to use Recursive to establish a registered Expression axis this is the case, we may want to discuss whether 0–1 is the best scale for the general idea of Expression, or if it might make more sense as something like 0–100. 
- On the note the "Expression" is too vague, I can understand this concern, and somewhat share it. However, in defense of Expression, it wouldn't be the only non-scientific axis name. On the contrary, all axes are somewhat open to design interpretation, because fonts are all about optical compensation and what makes sense for the specific intent of the family. That is, no two fonts will have the exact same black-to-white ratio in their `400` or `700` weight or handle an optical size of `32` in the exact same way. 

**My current opinion:**

I am somewhat leaning towards changing the axis name to Casual, because the Pros seem to outweigh the cons, principally that the name Casual better harmonizes with to the Monospace axis.

Of course, it is possible that Expression is a valid variable axis, and maybe Recursive shouldn't use it, anyway. If this is the case, I have taken an initial stab at an OT spec style of definition, below.

## Other questions

> can you define all the axes in the project source tree somewhere

Done at https://github.com/arrowtype/recursive/blob/master/README.md#variable-axes ([permalink](https://github.com/arrowtype/recursive/blob/4cd2edd024c374c1d0d29a567f23ccc35f94e2c0/README.md#variable-axes))

> with at least all the fields in the Microsoft Axes proposal repo?

Just to confirm, you'd like me to submit a PR to this repo, for both "Monospace" and "Casual"/"Expression"  correct, @davelab6? 

https://github.com/microsoft/OpenTypeDesignVariationAxisTags/tree/master/Proposals

## If Expression were to be registered

Expression might be defined more generally as something like:

**Description:** Used to vary the unique visual attitude or tonality of a given typeface

**Valid numeric range:** Values must be in the range 0 to 100.

Scale interpretation: Values can be interpreted as a percentage of the full range of creative expression possible at a given optical size. 

Recommended or required “Regular” value: A value in the range 20 to 80 is recommended.

**Comment by arrowtype** [comment]
Changing the axis name to Casual / `CASL`. 

https://github.com/arrowtype/recursive/commit/fa24e5ce98b3bd16e2d452564c025c37cd8e7a9f

It is a bit less fluent to use in language, but I agree that it's probably more user-friendly and makes sense in the long-run.
