### ISSUE TITLE
Some characters (outline shapes) don't respond to font weight changes on website

### ISSUE THREAD

**Issue by iansan5653** [arrowtype/recursive#257]
See the picture:
![image](https://user-images.githubusercontent.com/2294248/69198481-d505f900-0b02-11ea-9799-d9ab0bb149bc.png)

Note how the ▷ character and similar are not affected by the increased font weight.

**Comment by arrowtype** [comment]
Hey Ian, thanks for your interest in Recursive, and thanks for taking the time to file an issue!

It is true that those glyphs don't respond to weight, but that is intentional. The way I think of those, they are specifically to be empty/outlined icons, so making them thicker for bolder weights may actually degrade their utility. Is there a specific purpose for which you would need bolder versions of those shapes?

**Comment by iansan5653** [comment]
I don't have a specific purpose, but I noticed that they really stand out when paired with the bold glyphs so I assumed it was a bug. I would think that if these are ever used in combination with heavier weights of other characters, they will be pretty obvious.

**Comment by arrowtype** [comment]
![Kapture 2020-01-22 at 23 02 46](https://user-images.githubusercontent.com/45946693/72960545-58460400-3d6b-11ea-9a84-73d28c1d6e11.gif)

This is fixed and building into the VF as of https://github.com/arrowtype/recursive/tree/e882954365d4fafdf2fb43abeff99a28d615f32e/fonts_1.034/Variable_TTF.

I'll be updating the static fonts with this soon, as well, and make a proper release with this, then update the website. Thanks, @iansan5653!
