### ISSUE TITLE
Add Greek and Cyrillic support

### ISSUE THREAD

**Issue by cssobral2013** [arrowtype/recursive#348]

**Comment by arrowtype** [comment]
Hey, thanks for the request!

I would love to do this, but it won’t happen anytime soon due to the scope of work it would require (especially in this particular type family, due to its large variable designspace). 

It would take a very substantial investment from a client to pay for the time to make it happen. Maybe/hopefully someday!

**Comment by arrowtype** [comment]
+ one thing worth noting:

If you are looking for this feature for the font in code, it’s worth knowing that the metrics are compatible with many other monospace fonts. So, for example, if you set your font stack to include IBM Plex Mono and the generic system “monospace”, Cyrillic & Greek glyphs will display in fallbacks without disrupting the overall monospacing of your code.
