### ISSUE TITLE
Provide a way for users to generate custom fonts

### ISSUE THREAD

**Issue by joshtriplett** [arrowtype/recursive#356]
I'm enjoying using Recursive. However, I prefer the CRSV=1 look even for upright fonts. Would you consider providing static monospace fonts for CRSV=1?

(Alternatively, I'd love to have a guide for exporting a font file that contains multiple specific variants and hardcodes specific OpenType features such as ss02/ss05/ss07. I have no problem running a script to get the font I'd like.)

**Comment by kaushikgopal** [comment]
similar request to @joshtriplett here. Would be nice to have a mechanism for the devoted few, willing to go the extra mile and build static fonts for specific variants (For example, i love Mono SemiCasual, but just want to swap out the simplified @ symbol). If one had to build custom variants of Reco Mono SemiCasual with ss08 and ss11 (for example) what steps should they follow.

**Comment by arrowtype** [comment]
That’s a cool idea, @kaushikgopal! If there were a command-line way of doing this, would you be up for cloning a repo, installing some Python dependencies, and running a script with some args around axes & stylistic sets?

It would be a pretty big scope for me to make something like a website w/ UI for custom downloads, _but_ it would be pretty fun & relatively quick (I think 🤞) to make a repo that adapts [my `instantiate-code-fonts.py` script](https://github.com/arrowtype/recursive/blob/e13789e13389a5ed9be25191f3f461b6b9618fe2/src/build-scripts/make-release/instantiate-code-fonts.py) to generate fonts according to personal preference...

**Comment by joshtriplett** [comment]
@arrowtype Yes, I'd have no problem cloning a repository (or just *this* repository, no need to maintain a separate one) and running a Python script.

I also think this would make it much easier to resolve future differences in stylistic preferences by adding OpenType features.

**Comment by billziss-gh** [comment]
@arrowtype I second @joshtriplett's original request for releasing Monospace static fonts with CRSV=1.

**Comment by kaushikgopal** [comment]
> would you be up for cloning a repo, installing some Python dependencies, and running a script with some args around axes & stylistic sets?

@arrowtype : 💯  absolutely. I already imagined I'd have to do this and cloned the repo thinking i can find my way. So if we just have the instructions, that itself would be more than sufficient.

**Comment by kaushikgopal** [comment]
Fwiw: 

* [Iosevka](https://blog.jkl.gg/build-iosevka-font-mac-os/] goes that route of just expecting users to do it via script. 
* [Input Mono](https://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputMono&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=slash&asterisk=height&braces=0&preset=default&customize=please) has a pretty nice UI suggesting your latter approach (which i thought was pretty good too).

Honestly, a script with working instructions would be the best first step (imho) cause it allows all kinds of customization (vs having to build that additionally into a UI).

**Comment by wimstefan** [comment]
Iosevka is the best example indeed with a myriad of possible font variants that every user can choose and build quite easily ...
[Building instructions](https://github.com/be5invis/Iosevka#building-from-source) are quite easy and understandable.
And [here](https://typeof.net/Iosevka/) you can try and see how it looks like.

**Comment by arrowtype** [comment]
Nice! Yeah, I would like to (and may eventually) make a web UI for it, but for now I'm not quite sure how to hook up python on a server to generate those files, and the UI would definitely take some time to get right.

So, I will try to do a script for the short term. I think I'll be able to get to it in a couple of weeks, and will update this issue when I do!

**Comment by jkyeung** [comment]
First, let me say thanks for the work that went into this ambitious project, and congratulations for pulling it off!

I'm one of the weird ones who is actually interested in a "mildly proportional" font geared toward coding, a la Input Sans, so I'm looking forward to building customized static instances of Recursive (somewhat-)Sans with slashed zero to try out.

I will say I tried to set up my machine to just do builds as described in the README, but ran into some issues installing dependencies (perhaps because I'm on Windows). So I'm not sure I'll be able to use the script you're working on.

**Comment by kaushikgopal** [comment]
@arrowtype fwiw: I'd love to help build out the UI Web experience, if that's something you'd be interested in pursuing. I have some experience building out sites so could help out there.

**Comment by alerque** [comment]
I'd love to extend `fontship` to make this sort of thing a one-dependency and one-command operation.

**Comment by arrowtype** [comment]
Thanks for all the comments here!

I do think that the most users could get value out of a web UI (there are tons of new and/or busy coders who would visit a website, but not want to download a repo and mess with a command line script). At the same time, it would take the most time to design & build. I have actually made some progress on this front, but two things hold me back:

1. The challenge of making a custom range element with min, max, and value, plus step settings. I got somewhat close in Svelte, but it ended up being too big a time suck to complete (so far). But, once I nailed this component, the rest would probably be fairly straightforward. (🤞)

2. I'm not sure what the best/cheapest way might be to actually process the user requests and generate font downloads. The main tool for making partial instances from a variable font is FontTools Instancer, which runs on Python. Samsa JS miiight work for just static instances (I don't know offhand whether it supports more than that).

I haven't really looked too closely at FontShip yet, but it seems cool! I'll try to give it a closer read.

**Comment by kaushikgopal** [comment]
Thanks for looking into this!

This might be hacky or (potentially not even possible) but how crazy would it be to generate all permutations and keep em pre generated. Then just point to a simple CDN/download for the specific combination chosen by the user 🤷🏽‍♂️. 

Though, if there are too many permutations might not be the best route. At that point just investing in instructions and letting us install and fiddle with the python ourselves might work. 

Thanks again for your awesome work with this.

**Comment by arrowtype** [comment]
> How would it be to generate all permutations and keep them pre-generated, then just point to a simple CDN/download for the specific combination chosen by the user?

Good question! I _think_ this might be the approach that was taken for the excellent Input Mono [preview](https://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please) & [download](https://input.fontbureau.com/download/index.html?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please) tools.

I wrote [a script](https://github.com/arrowtype/recursive/blob/132c73d0c2a9d09a2f9fe7bcd8284da930ac99a2/docs/02c-axis_subset_permutations--jul_2020/how_many_possible_permutations.py) to determine how many permutations this would require for Recursive.

Results:

- 17984 permutations with possible axis ranges, stylistic sets, & code ligature options are included. This would be helpful if the tool also allowed custom downloads for purposes other than coding (e.g. for self-hosted use on the web – this would be somewhat useful, as Google Fonts currently strips out stylistic sets & `dlig` (code ligatures).
- 4960 permutations if variable axis ranges are excluded (e.g. if you were making a tool *only* for outputting static fonts for code, but not partial fonts for other purposes)
- 4528 permutations if if we excluded axis ranges, _really_ limited the weight options to only steps of 100 rather than 25 and capped it at wght=800, and limited italics to just 0, -9,-12, -15.

Total data:

- If we assume that 159 kb is an average size for these permutations (that’s the approximate size of each static code-specific font right now), permutations of static-only fonts would be 788,640 kb, or about 789 MB of data.
- If we assume that 160 kb is the size for _all_ permutations, that would be 2,697,600 kb, or about 2.7 GB of data. But in reality, if fonts with axis ranges are included, these would all be larger. As a wild guess, I imagine it might be around 5–10 GB of total data?

**Comment by arrowtype** [comment]
(Had to edit the permutation & data numbers to correct a small math error – others are obviously welcome to check my script for issues, if you are skeptical of the results!)

So, I think that those might be somewhat prohibitively large numbers to host, but maybe or maybe not. If we used python to generate the permutations & name them appropriately, we could use similar logic in JavaScript to download the appropriate files.

In the short term, a mini-repo to facilitate that kind of configuration might be appropriate. For the web project, I worry that there wouldn’t really be a budget appropriate to the level of time & effort it would take to produce.

**Comment by arrowtype** [comment]
Hmm, if we only allowed weights 400 & 700, it could be 4240 permutations, which starts to feel like a less intimidating number. People may get some benefit of going up or down by a bit, but if this were limited to code, that would be a reasonable limitation.

If we really limit it to coding and forget about custom axis ranges entirely, we could do something like this mockup:

<img width="1152" alt="recursive-gf_api_config-2020-07-26" src="https://user-images.githubusercontent.com/45946693/88485451-c13d4d00-cf43-11ea-8799-412aa4f7b384.png">


The RIBBI font options could either be menus (these would be 109 items long if we limited to 3 MONO, 3 Casual, 2 weights, & 3 slants, and cursive/roman). Or, probably better, they could expand into little configuration panels (similar to the minisite’s current sidebar). Other options could follow in on/off switches (I’ve basically copied the Figma design for OpenType features, as it is very good).

**Comment by kaushikgopal** [comment]
💯 i think your last comment makes a lot of sense. The custom axis is pretty sweet and powerful as an option but honestly  make sense for you to just pick strong default and limit the number of permutations.  Limiting the options does do disservice to how crazy customizable this font truly is but I think most folks wanting such a tool, probably only want it mostly to swap out specific characters.

Heck the mockup you have alone would be more than sufficient for most of the folks on this thread, i'd imagine.

--------------------

That being said 🤔, here's another starter suggestion/idea that might be simpler to pull of to begin with: instead of the output being a direct font download (which would definitely be more convenient), you could just output a customized [my `instantiate-code-fonts.py` script](https://github.com/arrowtype/recursive/blob/e13789e13389a5ed9be25191f3f461b6b9618fe2/src/build-scripts/make-release/instantiate-code-fonts.py), with command line instructions 🤷🏽‍♂️ on how to build the font (as an output).

If that works out well enough, you could just use github issues/wiki etc. 😋 as the source for the different permutations. I imagine the more popular ones would start to get covered pretty quickly that way.

Just spewing ideas/thoughts, so apologies if this is distracting.

**Comment by jkyeung** [comment]
> I wrote [a script](https://github.com/arrowtype/recursive/blob/baca411b15fb2b8cb7672ab700bd936c4d666c78/docs/02c-axis_subset_permutations--jul_2020/how_many_possible_permutations.py) to determine how many permutations this would require for Recursive.

Perhaps I'm misunderstanding what the possibilities are, but I believe your script doesn't count what it needs to.

In its current state (as I write this), it spits out the 7228 result, which is the sum of the 3132 choices based on the axis constraints and the 4096 choices based on the stylistic sets (`ss01`, `ss02`, etc.). But if I understand font compilation correctly, you have to multiply them.

For example, let's say you chose `MONO=0`, `CASL=0`, `wght=400`, `slnt=0`, and `CRSV=0`. Given that combination of axis inputs, you could then have 4096 possible stylistic set combinations.

Now, let's say I chose `MONO=0`, `CASL=0`, `wght=450`, `slnt=0`, `CRSV=0`. I could also choose among 4096 possible stylistic set combinations. If I understand static font files correctly, none of my 4096 possible font files would be the same as any of your 4096 possible font files (because all of yours would have weight of 400, while all of mine would have weight of 450). So now, just with the two of us, we already have 8192 possible font files. When someone else comes along and chooses a different weight, they also have *another* 4096 possible font files. And repeat this exercise for all the different choices for all the different axes.

So, what I believe you really have is 3132 * 4096 possible static instances, or about 12.8 million font files.

Incidentally, you can just do this mathematically. In the scenario modeled by the script, you have 3 possibilities for `MONO`, 3 possibilities for `CASL`, 29 possibilities for `wght`, 6 possibilities for `slnt`, and 2 possibilities for `CRSV`. Multiply all those together and you have 3132. You have 12 different stylistic sets, each of which can be on or off (2 possibilities each). Multiply all those together (2**12) and you have 4096.

Further constricting the weight options to steps of 100 and capping at 800 (6 weight choices, if you start at 300) and 4 different slants yields 3 * 3 * **6** * **4** * 2, or 432 choices among the 5 axes, *each* of which could have 4096 style set combinations, or about 1.8 million total combinations (not 423 + 4096).

With only 2 possible weights (400 and 700) instead of 6, you've further cut down the possibilities to 3 * 3 * **2** * 4 * 2 * 4096, or 589,824 total possibilities.

If my understanding is correct, it's quite impractical to just precompile all the possibilities, even with fairly severe limitations on the available choices.

**Comment by arrowtype** [comment]
Ahhh hahaha, I think you are very correct, and that made me literally laugh out loud. Okay, yes, precompliling 1.8 million font combinations is not practical (at least not on my laptop).

Yeah, I think that basically, it would either either require instancing with a JS library, or else a DIY script.

Thanks so much for correcting me on that!

**Comment by jkyeung** [comment]
> Okay, yes, precompliling 1.8 million font combinations is not practical (at least not on my laptop).

And even if you did, my desired instance wouldn't be among them!

> Yeah, I think that basically, it would either either require instancing with a JS library, or else a DIY script.

The DIY option isn't *too* bad, I think. You mentioned fontTools, which I do happen to use myself. I was able to install it just using pip on Windows, so I think most people should be able to do it as well.

My only issue with fontTools (I happen to use `mutator` instead of `instancer`, but it seems to me the only difference is that `mutator` doesn't allow ranges) is that I don't think the ready-made command-line modules (like `mutator` or `instancer`) handle stylistic sets. I would love to be proven wrong!

> Thanks so much for correcting me on that!

No problem! I'm glad you didn't take offense at it, obviously none was meant, and I'm still very impressed with what you have already achieved with this project.

**Comment by kaushikgopal** [comment]
👋 @arrowtype  : any chance you could look into providing a script that'll let us build a custom variant?

**Comment by arrowtype** [comment]
Okay, I’ve made a first draft of a customization script:

https://github.com/arrowtype/recursive-code-config

@kaushikgopal and whoever else is interested, please give it a try and let me know if it works, or if it seems like I’ve missed anything. Hope it works for you!

**Comment by arrowtype** [comment]
@jkyeung that may also be helpful to you. :) If it still doesn’t do what you’re hoping for, let me know and I’ll see whether it seems simple enough to add.

**Comment by arrowtype** [comment]
It would still maybe be cool to eventually make a website for this at some point, but https://github.com/arrowtype/recursive-code-config will hopefully work for motivated folks for the time being.

**Comment by jkyeung** [comment]
Thank you for doing this. It is indeed helpful, though with some rough edges yet. I'll continue to post issues to the [custom script project](https://github.com/arrowtype/recursive-code-config) as applicable.

**Comment by kaushikgopal** [comment]
Thanks @arrowtype : this works like a charm. I just tried it and generated a custom variant :). Sent in a PR for a quick requirements update, but other than that this is perfect 🙏🏽
