### ISSUE TITLE
Shape of uppercase C, G and S on Recursive Mono Casual 

### ISSUE THREAD

**Issue by haggen** [arrowtype/recursive#402]
Hi,

First of all; Recursive is, hands down, the absolute best looking font I've ever laid eyes upon. I'm a developer and I've been searching for _the font_ since I first opened up a text editor when I was about 10. Recursive is beyond-my-wildest-dream good. Thank you so much for this gift. ❤

Except... and I know this is a tiny winey atom-small nit pick and I absolutely understand if you dismiss me like we dismiss a cockroach crossing our path on the sidewalk, but the top part of uppercase "C", "G" and "S" annoys me a little.

![C, G and S uppercase using Recursive on Visual Studio Code, Dark+ theme.](https://user-images.githubusercontent.com/270076/92961957-8ab18800-f446-11ea-9b9f-a1293ef96521.png)

The overall shape of that top part end up looking a bit too sharp for my taste, like a little slope pointing to the right, specially on smaller sizes (~16px or less). Particularly for a developer who writes a lot using `PascalCase` or `camelCase` this end up a little distracting.

If, and again I know this is a big if, it would be at all possible to even out that top slope, like, make it take a more balanced, rounder shape, it would be riding-an-unicorn-through-fluffy-clouds-and-rainbows awesome!

I tried to make a preview of what I mean in Photoshop but I failed. I hope I managed to communicate well enough what my peeve is.

Hope you all have a great day, and thanks again! 🍻

**Comment by arrowtype** [comment]
Hey @haggen, thanks so much for the kind words, and thanks for taking the time to file an issue!

As someone who pays close attention to the details of letters, I get where you’re coming from. It’s part of the reason I make fonts!

To me, the unique shaping of the round letters is part of what makes Recursive Casual a “Casual” design. You may have already seen my process article about the family, but if not, I explain this more deeply in it: https://www.recursive.design/process/. At this point, I am (mostly) only editing a few limited things in the project that I feel will make the family better within its existing character set & styles.

So, that leaves you with two main options:

1. If you like the overall style of Recursive but want things to look a little more normal/utilitarian, you could either just use the Linear style, a SemiCasual style, or configure you exact preference along the _Casual_ axis using [Recursive Code Config](https://github.com/arrowtype/recursive-code-config). Personally, I tend to use a “Duotone” variant which use linear for some parts of syntax, and the Casual italic for comments, etc, with [a theme I’ve configured for this purpose](https://github.com/arrowtype/recursive-theme).

![image](https://user-images.githubusercontent.com/45946693/93001399-bb53f900-f4fc-11ea-8037-fd7bb40b342e.png)

2. This is an [OFL](https://github.com/arrowtype/recursive/blob/main/OFL.txt) font, so if you love the Casual style but want to fork/copy the project & edit the shaping of a few specific letters, you can! You could also, of course, hire a type designer to help you do so. If you’re not in a big hurry, I could find some time to customize something for you, or I could suggest a few other designers who might be available to help out!

I’m closing this issue because I won’t take immediate action on it, but I appreciate your time, and I am happy to chat further if you want.

**Comment by haggen** [comment]
I couldn't ask for a better response. <3 Thank you for taking the time. The Semi Casual seems to be nice compromise I should check it out. I like the Linear style, but I really fell in love with the Casual one. It's so fun and full of character while still retaining a sense of "serious business". Really spot on work! 👌

**Comment by arrowtype** [comment]
Thanks! Yeah, a lot of time went into making the style have lots of energy but also being useful at code sizes. I maybe mull this change over a little bit, and maybe experiment with tweaking those a little bit, and let you know if I change anything. But, thanks for understanding that things are pretty stable, and probably won’t receive many design changes from here.
