### ISSUE TITLE
Adding Recursive_Code to homebrew

### ISSUE THREAD

**Issue by patrickfatrick** [arrowtype/recursive#422]
This is really more of a question. I made a pull request on homebrew-cask-fonts [here](https://github.com/Homebrew/homebrew-cask-fonts/pull/2685) to add the Recursive_Code files there for easy consumption. However, one of the maintainers rejected it, calling out the messaging in your repo about adding this font to Google Fonts.

My question is: are the prebuilt "code" files going to be added to Google Fonts? Or is getting them via github releases going to continue to be the best way to get these files?

**Comment by arrowtype** [comment]
Hi @patrickfatrick, thanks for reaching out!

As far as I know, Google Fonts one intends to have *one* version of a font family up at a time. For Recursive, this means that they only show a small subset of the available styles of the main family (Sans Linear).

Because Recursive Code isn't really a single thing but really a few options, it would be hard to actually know what to say is the single 4-style (Regular, Italic, Bold, Bold Italic) family they would even host. I suppose if I had to pick one sub-family, I would pick the "Duotone" option that I use myself.

Potentially, Google Fonts would add Recursive Code someday if there were demand for it. The typical way to get this started would be to file an issue requesting it at GitHub.com/Google/fonts.

> My question is: are the prebuilt "code" files going to be added to Google Fonts? Or is getting them via github releases going to continue to be the best way to get these files?

So, my best guess is that, for at least another year or two but probably always, GitHub Releases will be the best way to get these.

If you haven't already checked out the customization repo, that is perhaps one better option still, depending if you want to customize anything. See GitHub.com/arrowtype/recursive-code-config

**Comment by patrickfatrick** [comment]
Thanks for the confirmation! Hoping to get this added to homebrew soon.
