### ISSUE TITLE
Unmerged path

### ISSUE THREAD

**Issue by raphaelbastide** [arrowtype/recursive#426]
**Problem description**
The path of the glyph seams to be not merged.

**Expected behavior**
If a border is applied to a glyph, this border should not be visible inside the body of the glyph.

**Screenshots**

![Screenshot_2020-12-12_11-03-04](https://user-images.githubusercontent.com/193122/101981012-f8e63080-3c69-11eb-8334-e167f2ff26a2.png)

**To Reproduce**
1. add a border to a glyph, with CSS `  -webkit-text-stroke-width: 1px; -webkit-text-stroke-color: var(--g0);` or with any graphic software.

**Environment (please complete the following information):**
- OS: Linux (Debian xfce)
- Browser: Firefox nightly
- Fonts: 1.069

**Additional context**

**Comment by raphaelbastide** [comment]
I just learnt that it is a technical specificity for variable fonts. Can be closed if confirmed.

**Comment by arrowtype** [comment]
Thanks for filling a good and detailed issue on this!

Yes, variable fonts can include outline overlap, and in many glyphs it is essential to do so in order to make it possible for them to interpolate between styles.

So, if you want to use outlined text, you have two options:

1. Use a static font. These have overlap removed.
2. If it's on the web, you could get clever and outline the element, then duplicate it in front and give the copy the same fill as the background, to cover the interior overlaid. This is obviously a bit intense for a workaround, though.

I'll close this, but let me know if you have any questions and I will try to answer!

**Comment by raphaelbastide** [comment]
Nice tips, thanks.
