### ISSUE TITLE
Duotone and semicasual pre-built main Recursive families

### ISSUE THREAD

**Issue by VSchris-code** [arrowtype/recursive#464]
Just from looking that there's only 4 fonts that _Recursive Code_ has, but with 4 casuality variants, totalling 16 since it's designed to fit all of the syntax highlighting needs, I knew there was something wrong. There is only two casuality variants in _Recursive Sans_ and _Mono_ (the main _Recursive_ families, _Recursive Main_ from now on), but there is twice as much in _Code,_ at the cost of less styles. To bridge the gap of variants between _Recursive Main_ and _Recursive Code,_ why not add Duotone and semicasual pre-built _Recursive Main_ families, in Opentype and Truetype respectively?
I know it's going to take some time, but I'd _love_ to see it happen.

**Comment by arrowtype** [comment]
Thanks for reaching out, @VSchris-code!

The styles included in the main family vs Code families are pretty intentional. A few notes on this:

-  There _could_ be more styles generated from the variable font, but 64 styles is already a lot more than most type families, and I want to present a system that is simple enough for someone to understand in their font menu. I probably haven’t done this perfectly, but I doubt that adding _more_ styles would make it simpler. Font styles need enough contrast to make sense in a menu, so it’s obvious what benefit comes from any given selection.
- The main family static fonts are most specifically intended for graphic design situations, like use in Adobe InDesign, where the font size could be anything, small to huge. The static fonts provided in the main fonts are parts of the family that have the most predictable outlines with the least potential issues, due to how the fonts were created & drawn. Something like “SemiCasual” can work okay in a code editor at text sizes, but is not something I want to suggest people use at large scales like posters or logos, without really thinking it through. It will just have a few less-than-ideal curves. If they _really_ want to do so, it’s available in the variable font or via custom instancing tools (more on that below).
- In a program like InDesign (or in a scenario like CSS for web development), a designer can easily set up their “Italic” styles to use a Casual setting, even if they are using a Linear setting for “Regular” text. So, something like “Duotone” would be redundant, as its purpose is to provide that Linear/Casual relationship for Regular/Italic styles in apps like VS Code (or Microsoft Word), which don’t allow such granular design choices from users.

## Custom instancing tools

If you want to create static fonts with specific styles, you can do so! 

- A really nice tool for this is Slice: https://github.com/source-foundry/Slice
- If you prefer using code to a GUI, take a look at [fontTools.instancer](https://fonttools.readthedocs.io/en/latest/varLib/instancer.html), which can be used either via a CLI or Python.

## But also

If you feel like I’ve missed something, I’m open to reconsidering. If you have a specific use case in mind, let me know, and I can perhaps make a suggestion to you, and consider whether a lot more people might have the same need.

**Comment by VSchris-code** [comment]
Yeah, sounds sort of, _sort of_ right. There's _Oddlini_ with _*360 friggin' styles.*_ And It's commercial, and available in MyFonts.
Adding semi-casual and duotone to _Recursive Main_ would get you _quite_ close to half as much as _Oddlini's_ style count, 180, while ours (_Recursive Main_) goes up to 128 with duotone and semi-casual.

**Comment by arrowtype** [comment]
Okay, thanks for your time! I think the system in place is good, but other opinions are fine, too. I don't think I'll change it without a deeper reason. However, if you feel that these styles would be really helpful, feel free to fork the project and add them (so long as you keep the OFL licensing in place).

**Comment by VSchris-code** [comment]
> Okay, thanks for your time! I think the system in place is good, but other opinions are fine, too. I don't think I'll change it without a deeper reason. However, if you feel that these styles would be really helpful, feel free to fork the project and add them (so long as you keep the OFL licensing in place).

Ok, take your time adding them, in spite of the reason not being _very_ deep.
