### ISSUE TITLE
[Web] Unexpected leading size

### ISSUE THREAD

**Issue by ng-hai** [arrowtype/recursive#494]
**Problem description**
I'm styling some button for my web apps, and noticing that the leading of this font is making the UI misalignment.

**Expected behavior**
The text should be centered with the icon

**Screenshots**
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19520278/141459225-3f109fd8-dbee-44b6-a7c2-d41cad6cd574.png">

**To Reproduce**
https://codesandbox.io/s/vigilant-satoshi-uf1f0?file=/index.html
https://uf1f0.csb.app

**Comment by arrowtype** [comment]
Thanks for the clear and detailed issue!

Shoot, I am fairly sure this is a regression from before, as a definite goal here is to vertically center the caps.

I'll look into this and try to release a fix, ASAP.

**Comment by arrowtype** [comment]
Okay, @ng-hai, I’m looking at this on my end, but I’m not seeing quite the same thing. It’s possible that I could be seeing a different version, e.g. something picked up from my locally installed "Recursive" font, or possibly a difference in rendering between my OS and yours.

That said, font line heights are a little tricky, and I obviously believe that your seeing an issue. So, thanks for reporting, and I hope we’re able to drill down into what and where the issue is!

Can you please tell me what OS and browser (including versions) that you are seeing the problem on?

Here’s what I have on macOS Catalina, 10.15.7 ... perhaps not _exactly_ pixel-perfect, but about as close as I expect browsers to get:

Firefox 96 (Nightly):
<img width="401" alt="image" src="https://user-images.githubusercontent.com/45946693/141666294-9191a85e-7cd0-461f-a82d-cb6c2593fd2f.png">

Chrome 95:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/45946693/141666309-ab7137df-e82d-44fd-bf2a-961579bac562.png">

Safari 13.1.3: 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/45946693/141666317-3e5298b4-baa4-4847-b70f-8416a65edc38.png">

And, running Windows 10 in VM Ware, with Edge 89 browser:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/45946693/141666474-bc770022-b687-4ccc-8b28-662ae70c4f29.png">

**Comment by arrowtype** [comment]
Just as a quick check of whether the locally-installed font on my computer was throwing things off, I just checked on my phone (iOS 14 Safari):

![image](https://user-images.githubusercontent.com/45946693/141683779-9bd9b931-3284-414a-8dcf-d18cea15f746.jpeg)

**Comment by ng-hai** [comment]
That's weird. I'm using font source from Google Fonts. Let me check on my friend's machines.

**Comment by ng-hai** [comment]
Ok, so the problem is Safari 15.1 on my Mac :(
Thank you for supporting me. Will let you know on product launching later.

**Comment by arrowtype** [comment]
Wait, sorry, let’s keep this open until we diagnose the specific problem. 

Are you saying that you didn’t see the same issue on a friend’s computer?

What version of macOS are you on? Apple changed a lot of type things (mostly for the better) in macOS 11 Big Sur. I’m a couple versions back for now (Catalina), but I could run something newer on an external SSD to better understand whether this is something I can improve!

**Comment by ng-hai** [comment]
I'm using MacOS Monterey 12.0.1 (21A559), Safari 15.1.
A fun fact that Edge 95 and Safari have the same issue, while Firefox Developer Edition works great. Maybe it's the Chromium problem.

**Comment by arrowtype** [comment]
Thanks, that context is really helpful!

Fonts include multiple, different pieces of metadata to express their line height / metrics. Different software pays attention to these differently. So, it's a bit of a nightmare to fully nail down. But, this gives me a specific target. I bet I just have to test a few changes to the metric metadata, and something should be the sweet spot to make all the browsers work well.

I'll try to look into this further today, and will make a release this week if I find a solution.

**Comment by arrowtype** [comment]
Okay, I’ve experimented a bit with this, but so far, it’s inconclusive.

Can you please screenshot what you see in [the two groups of buttons here](https://codepen.io/thundernixon/pen/wvqNGOe), in Safari vs Firefox?

On my end, when I test this in Safari 15.1 on a macOS Monterey, the text is misaligned a little bit, though not to the extent it is in the top screenshot of this thread. And, the Google Fonts vs Test versions seem to render the same. On Firefox (also macOS Monterey), the problem doesn’t show. But, I’m still curious whether how this might look on your end, @ng-hai.

Thanks for bearing with me in this issue!

(For my future self: in this test font, I set the winAscent equal to typo Ascender, and winDescent equal to typo Descender. It isn’t like this in the official release versions, because (I think) winAscent needs to be higher to avoid accent cropping in various Windows apps. But, I’m not sure whether it makes a difference in line heights.)

**Comment by ng-hai** [comment]
Safari 15.1
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/19520278/142349928-f4fcfe69-4978-4fe1-a930-40039cc94ccc.png">

Firefox
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/19520278/142349999-d4c344bd-0d33-4889-a0d4-f2cbf2f14236.png">

It seems there is no issues as we're facing 😕

**Comment by arrowtype** [comment]
Shoot, I’ve realized that I had a typo in those SVGs, and they weren’t quite square. -_- I’ve adjusted them to be circles, and double-checked that they aren’t ellipses.

I also realized that it would be useful to add a third font for comparison, so I’ve added a column using Roboto. Sorry to ask again, but could you please screenshot this page? Thanks so much!

https://codepen.io/thundernixon/full/wvqNGOe

**Comment by ng-hai** [comment]
No problem :)
Safari 15.1
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19520278/142570360-2d6048b6-b25a-4f05-a67b-4c0a7690eb0e.png">

Firefox Developer Edition
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19520278/142570478-66c57753-e5bd-45d8-8cf4-846e9083b953.png">

Edge 95
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19520278/142570561-e2d1e1b7-ed4b-4cfa-b97b-2efa18292129.png">

**Comment by arrowtype** [comment]
Okay, thanks again for trying that and posting the screenshots!

I now can actually replicate this on my end, though it depends on zoom. At some zoom levels, the type "rounds up" to a pixel line where things are off-center. At other zoom levels, it looks perfectly centered. Roboto, meanwhile, seems to "round down" to a lower pixel, some of the time.

I’ll try to inspect Roboto a little more closely to see whether it sets metrics in a way that might cause it to look more close to the vertical center, more of the time.

**Comment by ng-hai** [comment]
Awesome, really looking forward to see upcoming release.

Just notice an interesting trick, if I use Flexbox Center, it will result this
<img width="326" alt="image" src="https://user-images.githubusercontent.com/19520278/143060299-369a25cd-3fdb-42c9-be08-a6f172d8f0e3.png">

But if I use Flexbox Stretch, the result is unexpectedly correct 😄
<img width="313" alt="image" src="https://user-images.githubusercontent.com/19520278/143061330-0b9559e5-7dff-4000-8f64-8d7e82e60aec.png">

**Comment by ng-hai** [comment]
The icon actually stays the same, and this is the first time I use stretch for button styling, but it seems getting great result :)

**Comment by ng-hai** [comment]
![Uploading image.png…]()

**Comment by ng-hai** [comment]
Dont know why using same code but different project, the result is still mismatch
<img width="832" alt="image" src="https://user-images.githubusercontent.com/19520278/143557017-e5218cb6-1bdb-4f30-9ae8-875f9b0d260e.png">

**Comment by arrowtype** [comment]
Thanks for the updates, @ng-hai! I’ve asked some smart folks, and I’m hoping someone might have a helpful suggestion. Sorry I couldn’t figure this out already, but I won’t be giving up on it!

**Comment by arrowtype** [comment]
Sorry, I haven’t forgotten about this, but I have just had many other things pop up, and no direct funding here, so it has been slightly pushed to the side.

I’ve recently updated my main computer to macOS Monterey, so this is on my mind again.

In testing, I see that the font line height is centered as intended at some font sizes / zoom levels, but not others. Normally, I’d speculate that this might indicate that the issue is something to do with font hinting. However, the Recursive variable font doesn’t have hinting, so that can’t be the issue.

It could also be an issue of how macOS renders variable vs static fonts ... I wanted to test this, so I’ve updated the CodePen page. It’s a little hard to tell for sure, but it does seem like the variable font is rendered just a bit thicker and sometimes at slightly different line heights, depending on zoom/size.

https://codepen.io/thundernixon/full/wvqNGOe

@ng-hai, if you’re still up for it, could you take a look at the codepen again and let me know if you see a difference between the left and center columns of buttons? It may be useful to zoom in/out (command - and command +), to further test it.

**Comment by ng-hai** [comment]
It looks great on every browser that I have installed 💯

**Comment by arrowtype** [comment]
Sorry, can you clarify... does the static font look great in every browser, or also the test font?

**Comment by arrowtype** [comment]
Woah! I wonder if maybe Apple fixed this issue in an update between November and now. 🤔

I’ve updated the CodePen for one more question: does the `GF Variable` look the same to you as the `GF Static` and `Test Font`?

https://codepen.io/thundernixon/full/wvqNGOe

**Comment by ng-hai** [comment]
Yes they're all the same

Safari
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/19520278/162041952-666c3c39-4050-4733-ba8b-11e156dc1628.png">

Firefox Dev Edition
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/19520278/162042001-cbd58d66-4982-41f1-94ce-8191933f63dd.png">

Chrome
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/19520278/162042021-cb370645-37af-4381-aabf-e789a8221e19.png">

Oryoki (Chrome 58) - but you should ignore it 🤣 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/19520278/162042177-d8a718e8-483e-4e7a-84aa-5f939b449ac6.png">

**Comment by arrowtype** [comment]
Amazing, thanks for checking and letting me know! Ha, I love when font problems are solved by software / OSes, so I don’t have to find some kind of hack to make them work as they should.

Oryoki is interesting – I hadn’t heard about it until now, but it looks like a cool browser project! Based on your screenshot, it looks like it currently doesn’t support `.woff` files (the left column) or variable fonts (the middle two columns).

**Comment by arrowtype** [comment]
Darn, it looks like Oryoki hasn’t been updated in about 4 years. I wish it had more support!

**Comment by ng-hai** [comment]
Haha me too
