### ISSUE TITLE
bug: Lowercase `l` rendering as uppercase `L`

### ISSUE THREAD

**Issue by smsegal** [arrowtype/recursive#497]
**Problem description**
I'm trying to configure [WezTerm](https://wezfurlong.org/wezterm/index.html) to use this font. As it supports opentype features as HarfBuzz flags, I'm attempting to use the variable version of the font in to get hinting etc. 

When the font is set (even without any opentype flags set), lowercase `l`s are rendering as uppercase in WezTerm. 

**Expected behavior**
When the terminal emulator is set to use the `Recursive` font, letters should be rendered in the proper case.

**Screenshots**
![image](https://user-images.githubusercontent.com/7110093/147957300-0f380bd7-abdc-4457-9b8c-2c0728e3a7dd.png)
(Note: this screenshot shows some of the opentype flags set, but this occurs with and without them set)

**To Reproduce**
1. Download the latest WezTerm for MacOS
2. Set a minimal configuration file with the font set:
```lua
-- in ~/.config/wezterm/wezterm.lua
local wezterm = require("wezterm")
return {
  font = wezterm.font({
	    family = "Recursive",
	    stretch = "Normal",
	    weight = "Regular",
	  })
}
```
4. Observe the incorrectly rendered `l`s. 

**Environment (please complete the following information):**
- OS: MacOS 12.1
- Fonts: v1.084

**Additional context**
I've opened a bug report for this in the WezTerm repo: https://github.com/wez/wezterm/issues/1496
It was suggested there that this might be an issue with conflicting stylesets and how they handle the `l` character. I'm not familiar enough with font internals to say.

**Comment by arrowtype** [comment]
Hi @smsegal, thanks for taking time to provide such clear documentation of the problem! Sorry I didn’t catch this earlier.

My first guess is that the system is activating the `MONO` variable axis, but without correctly applying the `rvrn` feature that swaps from the default `MONO=0` (Sans) forms to the `MONO=1` (Monospaced) forms. You can also see the issue in the `f r i` g0lyphs, thought it is less of a legibility problem there.

My main suggestion is to use one of the static monospace fonts, rather than the full variable font (which is really more useful when used on websites). I would recommend one of the two options documented in the project readme in the section [Font usage in Code Editors](https://github.com/arrowtype/recursive#font-usage-in-code-editors).

**Comment by arrowtype** [comment]
Potentially, the font could use the italic form of the `l`, which is less ambiguous, and would be legible in both the Sans and Mono styles, if `rvrn` fails to activate. But, this would take a fair bit of replumbing in the font, so I may not be able to make this change very soon.
