### ISSUE TITLE
Recursive Sans Linear displays to thin in pdf files

### ISSUE THREAD

**Issue by RFV** [arrowtype/recursive#518]
When exporting from Libreoffie writer to pdf files, the font is too thin in the pdf file.
I have exported other vairbale fonts to pdf files and they seem to display normally.
![image](https://user-images.githubusercontent.com/1437122/225881083-8f3039df-c21a-475a-9556-b68cea443192.png)
![image](https://user-images.githubusercontent.com/1437122/225881490-48ebbed5-8510-4fd4-9525-84d7caf7fe82.png)
![image](https://user-images.githubusercontent.com/1437122/225881588-7bf47f64-5d62-41f5-ac9f-4fd6a7b5c50d.png)

**Comment by arrowtype** [comment]
Hi @RFV, thanks for taking the time to file this issue!

I am fairly certain that this is a limitation of Libre Office Writer’s PDF generation flow. In general, I advise using static fonts for anyone doing print-centric design and exporting to PDFs (even in Adobe tools like InDesign).

### To explain a little further...

Variable fonts have a “default style” which is rendered by software that hasn’t been upgraded to properly render variable fonts. That software still reads the basic shape data (the default style), but can’t interpret the newer data tables that say how variable axes move vector points around to achieve non-default styles. Most likely, Libre Office hasn’t upgraded their PDF export to handle variable fonts.

The default style of Recursive VF is Sans Light, so that is the fallback that exported for you.

(The default style is decided by how a font is built from source drawings.)

### Why did the other fonts work, then?

- Arial is not currently available as a variable font (as far as I know). So, you were using static fonts there.
- Poppins is not widely available as a variable font – for example, the Google Fonts download of the family only gives static fonts. You were likely using static fonts there, too.
- Golos Text VF has a minimum weight of 400 (regular), so its default style is basically a static font at weight 400. If you look closely, you can see that the bold style used for a heading in Golos Text VF _also_ exports to PDF at that default weight, rather than being bold.

## A test

Where did you get your specific version of Poppins? 

If you uninstall that, [install this variable version](https://github.com/itfoundry/Poppins/tree/67ac6b8777c31c3c6a2c1141d512b9c4a1e6ea5f/variable/TTF%20(Beta)), and restart your computer, does Poppins still export as a Regular weight? 

It appears that its default weight is 100, so my guess is that it will exhibit the same limitation as the Recursive variable font.

## Advice

In the future, if you want to check the default style of a variable font, one handy tool is [WakamaiFondue](https://wakamaifondue.com/beta/) (“What can my font do?”).

You can drag a VF into their, and then scroll to check the “Variable” section. The style there will show the default style.

As an example, in the beta VF of Poppins, that default is Thin:

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/45946693/225953709-0bb02220-1a10-468b-b70d-07156d81fc15.png">

In another project of mine, AT Name Sans, the default is Text Bold:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/45946693/225953910-c372cd0e-e3bb-41d5-94f5-61241159bcf5.png">

If you really need a variable font to have a default style of Regular, this is now possible with the FontTools Instancer, but the main solution is to just use static fonts for print design, and variable fonts for web design, or design where you can outline the text before exporting for printing (e.g. logo design).

I’ll close this issue for now, but if you find evidence that this really is specific to Recursive rather than a LibreOffice issue, we can re-open it. 

Thanks again!

**Comment by RFV** [comment]
Upgrade fixed the problem. Thank you. Recursive is my new defualt font.
