### ISSUE TITLE
Double arrows

### ISSUE THREAD

**Issue by matj1** [arrowtype/recursive#523]
### Is your feature request related to a problem? Please describe.

Double arrows are missing in Recursive, so a fallback font is used for them, which looks bad.

![code in Recursive with unicode double arrows rendered in a fallback font](https://github.com/arrowtype/recursive/assets/22873928/ef9b18c5-8332-4124-850c-689d04e5dd40)

### Describe the solution you'd like

Glyphs for double arrows (⇐ ⇑ ⇒ ⇓) included in Recursive. There are code ligatures for double arrows, so maybe they could be used.

### Describe what you've tried so far

I tried to type double arrows in various versions of the font, and a fallback font was always used for them.

### Additional context

I use Recursive Sans Linear Static, but I expect the glyphs in variants of Recursive.

**Comment by arrowtype** [comment]
Hey @matj1, are you literally using the unicode characters for these double arrows (⇐ ⇑ ⇒ ⇓), or are you using code ligatures? Out of curiosity, which language are you programming in?

Just to check, this isn’t solved by the recent PR to the rec code config project, is it? https://github.com/arrowtype/recursive-code-config/pull/25

**Comment by matj1** [comment]
I am using literal Unicode arrows. The font is Recursive Sans Linear Static, so it is unrelated to the configurator. Rather, this issue made me discover the configurator.

The language is Scala. The example was made to show different Unicode arrows and how their styles don't match. I found the issue in different code.

Later, I found out that [Unicode arrows are deprecated in Scala](https://github.com/scala/scala-dev/issues/585), but I use them in a personal project, so I use them anyway.

**Comment by arrowtype** [comment]
Okay, thanks for the follow-up, that is very helpful.

To be honest, it takes a large amount of time (multiple hours) to add a single glyph to Recursive, because it actually requires drawing that glyph 12–24 times (depending whether it is similar or different along the MONO axis. Double arrows would be quicker to add than a more complex glyph (something with more curves, like an fleuron or something), but they would still take quite a bit of time. So, unless I am commissioned to do so, I can’t generally invest that time into a free project. I am open for commissions, but this kind of project mostly comes from companies, rather than individuals.

If you do want to use Recursive in your project, but also have support for double arrows, I recommend finding a fallback font that matches the spacing and general sizing of Recursive. Because Recursive doesn’t have those glyphs, it will allow the fallback font to appear, and this can look pretty good. Fonts that can work pretty well are IBM Plex Mono (great for e.g. Cyrillic) and Source Code Pro (which includes double arrows). Both of these have similar monospace widths and similar overall sizing / “vertical” metrics like x-height and cap height.

Hope that helps!
