### ISSUE TITLE
Map slant axis for more accurate slant control

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/recursive#59]
I'm not sure whether users need _exact_ control over the degree of slant for Recursive. However, if they do, the slant axis will need an `avar` map.

https://github.com/fonttools/fonttools/pull/1079#issuecomment-339379606

Here's a script to generate that mapping: 

https://gist.github.com/jenskutilek/f328f2ca250e8b9ebad0fb398a5a64c1

**Comment by arrowtype** [comment]
Two slight complexities of this: 
- The furthest Slant value is `-15`, but that corresponds to a real angle of most vertical paths at 14.04°
- The cursive forms of glyphs are activated when `slnt` goes beyond `-14`. 

So, the avar could do the following:
- map values of `0` to `-14` to real angles up to 14° (it could potentially go to 14.04°, but that might be pointlessly specific)
- map values of `-14.01` to `-15` to `-14.04`

**Comment by arrowtype** [comment]
This issue is solved in the designspace updates of https://github.com/arrowtype/recursive/pull/435.

I will close this once I build those updates into a release. For now, here is the updated VF:

[recursive-MONO_CASL_wght_slnt_ital--full_gsub-VF.ttf.zip](https://github.com/arrowtype/recursive/files/5845681/recursive-MONO_CASL_wght_slnt_ital--full_gsub-VF.ttf.zip)

**Comment by arrowtype** [comment]
Closed with https://github.com/arrowtype/recursive/releases/tag/v1.072
